# Interface contract — Project

_Generated by `agentic-agnostic-kit`. This file is the contract specific to this project, complementing the global contract (`~/.agents/AGENTS.md`)._

## [PRIORITY] Project contract vs global contract

- This file takes priority over the global contract for anything specific to this project (stack, internal conventions, workflows).
- The global contract remains the reference for anything this file doesn't cover (personality, security, git, operational caution).

## [STACK] Technical stack

_(to be filled in — language, framework, package manager, architecture)_

## [CONVENTIONS] Internal project conventions

_(to be filled in — e.g. naming conventions, folder structure specific to this project, recurring business rules)_

## [WORKFLOWS] Project-specific workflows

_(to be filled in — e.g. build/test/deploy commands specific to this project, git provider, environments)_

## [ARCHIVES] Logging validated functional studies and plans

As soon as a plan, analysis, or functional study is validated by the user for implementation, log the complete artifact in a local `.md` file under `ARCHIVES_R/{model}-analyses/` (e.g. `ARCHIVES_R/claude-analyses/`, `ARCHIVES_R/gemini-analyses/`, `ARCHIVES_R/opencode-analyses/`, `ARCHIVES_R/qwen-analyses/`). Naming: `YYYY-MM-DDTHH-MM-short-topic-name.md`.

**Strict ban on external publication**: every deliverable stays strictly local, in `.md` format, under `ARCHIVES_R/`. Never publish to a third-party Cloud/Artifact service.

## [ADR] Logging architecture decisions

As soon as a non-trivial technical choice is settled (structural dependency adopted or dropped, integration mechanism, durable bug workaround, convention change), log it as an Architecture Decision Record under the project's `ADRs/` directory. Naming: `NNNN-short-kebab-title.md` (four digits, next free number). See `ADRs/README.md` for the expected format (Status / Context / Decision / Consequences). Don't write an ADR for day-to-day implementation details — only decisions a future contributor would otherwise have to reverse-engineer.

## [BACKLOG] Logging and maintaining pending ideas

Log any pending idea, ideation, decision to revisit, or backlog item in `Backlog.md` at the project root — don't let it get lost in conversation. Append a status marker after each item's number (e.g. `# 3. DONE`, `# 5. IN PROGRESS`, `# 7. (idea)`) and keep it current: update the marker in place as soon as an item's status changes, rather than adding a new item for the same topic. Before starting on an item, check the code first for traces of an unfinished implementation.

## [GRAPHIFY] Knowledge graph

If a knowledge graph exists under `graphify-out/` in this project:
- **Before any broad exploration**: query the graph first via `graphify query "<question>"`, `graphify path "<A>" "<B>"`, or `graphify explain "<concept>"`.
- **Post-change update**: after any structurally significant code change, run `graphify update .` to keep the graph current (AST-only, 0 API cost).
