# Universal interface contract — Global source of truth

_Generated by `agentic-agnostic-kit`. This file is the global (Home) source of truth for every AI/LLM agent on this system. Each agent reaches it via a short stub in its own config directory._

## [PRIORITY] Global contract vs project contract

- This file applies everywhere, on every project, by default.
- If a project has its own `<project>/.agents/AGENTS.md`, that one takes priority for anything specific to that project.

<!-- agentic-agnostic-kit:begin:preamble v1 -->
## [PREAMBLE] Critical rules (loaded on every session, even truncated)

_This section is extracted as-is by the SessionStart hook and injected first — keep it short (a few lines) and put only what MUST apply from the very first message, even if reading the rest of the contract is delayed. Edit it with your own rules: response language, tone, greetings, response format, etc._

- (to be filled in by you — e.g. response language, tone, format)
<!-- agentic-agnostic-kit:end:preamble -->

## [CORE] Fundamental rules

_(to be filled in — personality, communication, expected rigor)_

## [REDACTION] Prose — no hard-wrap

For any prose meant to be read as rendered output (README, docs, reports, emails, messages): a paragraph stays on a single logical line, never a manual line break in the middle of a sentence just to fit a fixed column width (a habit inherited from code/comment formatting, unsuited to Markdown or text meant to be rendered). Leave line wrapping to the renderer's/editor's automatic wrap. Only break a line manually for an actual structural boundary (end of paragraph, list item, table row).

## [CREDIT] Attribution

_(to be filled in — e.g. credit/attribution policy in commits, docs)_

## [SECURITY] Branch and merge management

_(to be filled in — e.g. autonomous merge/rebase policy)_

## [FILES & CMD] Operational caution

_(to be filled in — e.g. validation before editing, confirmation before deletion)_

## [ARCHIVES] Logging validated functional studies and plans

As soon as a plan, analysis, or functional study is validated by the user for implementation, log the complete artifact in a local `.md` file under `ARCHIVES_R/{model}-analyses/` (e.g. `ARCHIVES_R/claude-analyses/`, `ARCHIVES_R/gemini-analyses/`, `ARCHIVES_R/opencode-analyses/`, `ARCHIVES_R/qwen-analyses/`). Naming: `YYYY-MM-DDTHH-MM-short-topic-name.md`.

**Strict ban on external publication**: every deliverable stays strictly local, in `.md` format, under `ARCHIVES_R/`. Never publish to a third-party Cloud/Artifact service.

## [GRAPHIFY] Knowledge graph — per-project method

The code graph (`graphify`) is **per project**, never global at Home:
- Before exploring code blindly (broad grep, exploratory reading), query the graph first if present in the project (`graphify-out/`): `graphify query "<question>"`, `graphify explain "<Symbol>"`, `graphify path "A" "B"`.
- After any change that significantly alters the code structure, regenerate via `graphify update .` (incremental, AST-only).
