import { bold, dim, green, yellow, cyan } from "./colors.js";
import { relPath, successBox } from "./ui.js";

const OWNERSHIP_STATUS = {
  absent: { icon: green("+"), text: "New file — will be created" },
  "kit-owned": { icon: green("✓"), text: "Generated by a previous run of this kit" },
  "user-owned": {
    icon: yellow("⚠"),
    text: "You've customized this file — review before confirming",
  },
  mixed: {
    icon: yellow("⚠"),
    text: "Changed outside the kit since the last run — review carefully",
  },
};

const KIND_ACTION = {
  create: "will be created",
  "update-merge": "a section will be updated, the rest of the file is left untouched",
  "update-replace-section":
    "the kit's block will be refreshed, any content you added yourself is preserved",
  remove: "will be removed",
};

export function formatFileOpPreview(fileOp, { verbose = false, cwd = null } = {}) {
  const status = OWNERSHIP_STATUS[fileOp.ownership] ?? { icon: "-", text: fileOp.ownership };
  const alreadyUpToDate =
    fileOp.ownership === "kit-owned" && fileOp.diffPreview.includes("no textual difference");
  const shownPath = cwd ? relPath(cwd, fileOp.targetPath) : fileOp.targetPath;

  const lines = [];
  lines.push(`\n${status.icon} ${bold(shownPath)}`);
  if (alreadyUpToDate) {
    lines.push(dim("  Already up to date — nothing to do."));
  } else {
    lines.push(dim(`  ${status.text}.`));
    if (fileOp.ownership !== "absent") {
      lines.push(dim(`  ${KIND_ACTION[fileOp.kind] ?? fileOp.kind}.`));
    }
  }

  if (verbose && !alreadyUpToDate) {
    lines.push(dim("  --- diff ---"));
    for (const line of fileOp.diffPreview.split("\n")) {
      const colored = line.startsWith("+")
        ? green(line)
        : line.startsWith("-")
          ? yellow(line)
          : line;
      lines.push(`  ${colored}`);
    }
  } else if (!verbose && !alreadyUpToDate && fileOp.ownership !== "absent") {
    lines.push(dim("  (run with --verbose to see the full diff)"));
  }

  return lines.join("\n");
}

export function formatSummary(applied, { cwd = null, nextSteps = [] } = {}) {
  if (applied.length === 0) {
    return "No change applied.";
  }
  const dryRun = applied.some((a) => a.dryRun);
  const appliedCount = applied.filter((a) => a.applied || a.dryRun).length;
  const ignoredCount = applied.length - appliedCount;

  const lines = [`\n${bold("Details")}`];
  for (const a of applied) {
    const tag = a.dryRun ? cyan("[dry-run]") : a.applied ? green("[applied]") : dim("[ignored]");
    const p = cwd ? relPath(cwd, a.targetPath) : a.targetPath;
    const backup = a.backupPath ? dim(` (backup: ${cwd ? relPath(cwd, a.backupPath) : a.backupPath})`) : "";
    lines.push(`  ${tag} ${p}${backup}`);
  }
  lines.push(successBox({ appliedCount, ignoredCount, dryRun, nextSteps }));
  return lines.join("\n");
}
