#!/bin/bash
# PROJECT SessionStart hook generated by agentic-agnostic-kit.
#
# A project-scope SessionStart hook (local .claude/settings.json or
# .gemini/settings.json) COMPLETELY REPLACES (no merge) the hook for the
# same event/matcher defined at the Home level (precedence rule documented
# in the agentic-agnostic-kit development notes).
# This hook must therefore itself carry the instruction to read the global
# contract, in addition to the project contract - otherwise the global
# contract is never read again from this project.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
CONTRACT_PATH="$PROJECT_DIR/.agents/AGENTS.md"
GLOBAL_CONTRACT="$HOME/.agents/AGENTS.md"
MAX_BYTES=4096

if [ ! -f "$CONTRACT_PATH" ]; then
  exit 0
fi

GLOBAL_BLOCK=""
if [ -f "$GLOBAL_CONTRACT" ]; then
  GLOBAL_BLOCK="
2. ALSO read ${GLOBAL_CONTRACT} in full (Read tool) - global baseline,
   valid on every project. In case of conflict with the project contract
   below, the project contract takes priority (project-specific rules)."
fi

# --- Cross-agent graphify auto-alignment ----------------------------------
if command -v graphify >/dev/null 2>&1; then
  GRAPHIFY_SYNC_LOG="$PROJECT_DIR/.agents/hooks/.graphify-sync.log"
  {
    echo "--- sync $(date -u +%Y-%m-%dT%H:%M:%SZ) ---"
    for _platform in opencode antigravity; do
      (cd "$PROJECT_DIR" && timeout 8 graphify "$_platform" install --project) || true
    done
  } >>"$GRAPHIFY_SYNC_LOG" 2>&1 || true
fi

# Dynamic discovery of local product skill(s), with no name hardcoded at
# render time: every .agents/skills/<name>/SKILL.md folder is flagged to
# the agent. Zero assumption about the skill's content or usefulness -
# just its existence.
SKILL_BLOCK=""
if [ -d "$PROJECT_DIR/.agents/skills" ]; then
  for skill_dir in "$PROJECT_DIR"/.agents/skills/*/; do
    [ -f "${skill_dir}SKILL.md" ] || continue
    skill_name="$(basename "$skill_dir")"
    SKILL_BLOCK="${SKILL_BLOCK}
   - Call the Skill tool with skill=\"${skill_name}\"."
  done
  if [ -n "$SKILL_BLOCK" ]; then
    SKILL_BLOCK="
0. Load the local product skill(s), before any other step:${SKILL_BLOCK}"
  fi
fi

PREAMBLE="PROJECT INTERFACE CONTRACT — MANDATORY PREAMBLE (full contract: ${CONTRACT_PATH})

=== TO DO BEFORE ANY OTHER ACTION, IN THIS ORDER ===${SKILL_BLOCK}
1. Read ${CONTRACT_PATH} in full (Read tool). The preamble below is
   an excerpt: it does not replace the contract.${GLOBAL_BLOCK}
These steps are required even if the user's first question seems
trivial or unrelated to code. Do not produce a substantive answer before that."

PREAMBLE_BYTES=$(printf '%s' "$PREAMBLE" | wc -c | tr -d ' ')

if [ "$PREAMBLE_BYTES" -gt "$MAX_BYTES" ]; then
  PREAMBLE="PROJECT INTERFACE CONTRACT — FALLBACK PREAMBLE

WARNING: this hook's full preamble is ${PREAMBLE_BYTES}
bytes, above the ${MAX_BYTES} limit. It risked being truncated
by the harness. Report this to the user.

TO DO BEFORE ANY OTHER ACTION: read ${GLOBAL_CONTRACT} then
${CONTRACT_PATH} in full (Read tool)."
fi

jq -n --arg preamble "$PREAMBLE" '{
  "hookSpecificOutput": {
    "hookEventName": "SessionStart",
    "additionalContext": $preamble
  }
}'
