#!/usr/bin/env node
// PROJECT SessionStart hook generated by agentic-agnostic-kit (Node.js engine).
//
// A project-scope SessionStart hook (local .claude/settings.json or
// .gemini/settings.json) COMPLETELY REPLACES (no merge) the hook for the
// same event/matcher defined at the Home level.

import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const SCRIPT_DIR = path.dirname(__filename);
const PROJECT_DIR = path.resolve(SCRIPT_DIR, "..", "..");
const CONTRACT_PATH = path.join(PROJECT_DIR, ".agents/AGENTS.md");
const GLOBAL_CONTRACT = path.join(os.homedir(), ".agents/AGENTS.md");
const MAX_BYTES = 4096;

if (!fs.existsSync(CONTRACT_PATH)) {
  process.exit(0);
}

let globalBlock = "";
if (fs.existsSync(GLOBAL_CONTRACT)) {
  globalBlock = `\n2. ALSO read ${GLOBAL_CONTRACT} in full (Read tool) - global baseline,\n   valid on every project. In case of conflict with the project contract\n   below, the project contract takes priority (project-specific rules).`;
}

// --- Cross-agent graphify auto-alignment ----------------------------------
try {
  execFileSync("which", ["graphify"], { stdio: "ignore" });
  const graphifySyncLog = path.join(PROJECT_DIR, ".agents/hooks/.graphify-sync.log");
  const dateStr = new Date().toISOString().replace(/\.\d+Z$/, 'Z');
  let logContent = `--- sync ${dateStr} ---\n`;
  for (const platform of ["opencode", "antigravity"]) {
    try {
      const out = execFileSync("graphify", [platform, "install", "--project"], {
        cwd: PROJECT_DIR,
        timeout: 8000,
        encoding: "utf-8",
      });
      logContent += out + "\n";
    } catch (e) {
      logContent += (e.stdout || "") + "\n" + (e.stderr || "") + "\n";
    }
  }
  fs.appendFileSync(graphifySyncLog, logContent);
} catch (e) {
  // graphify not found or failed, ignore silently
}

let skillBlock = "";
const skillsDir = path.join(PROJECT_DIR, ".agents/skills");
if (fs.existsSync(skillsDir) && fs.statSync(skillsDir).isDirectory()) {
  const dirs = fs.readdirSync(skillsDir, { withFileTypes: true });
  for (const d of dirs) {
    if (d.isDirectory()) {
      const skillFile = path.join(skillsDir, d.name, "SKILL.md");
      if (fs.existsSync(skillFile)) {
        skillBlock += `\n   - Call the Skill tool with skill="${d.name}".`;
      }
    }
  }
  if (skillBlock) {
    skillBlock = `\n0. Load the local product skill(s), before any other step:${skillBlock}`;
  }
}

let preamble = `PROJECT INTERFACE CONTRACT — MANDATORY PREAMBLE (full contract: ${CONTRACT_PATH})

=== TO DO BEFORE ANY OTHER ACTION, IN THIS ORDER ===${skillBlock}
1. Read ${CONTRACT_PATH} in full (Read tool). The preamble below is
   an excerpt: it does not replace the contract.${globalBlock}
These steps are required even if the user's first question seems
trivial or unrelated to code. Do not produce a substantive answer before that.`;

const preambleBytes = Buffer.byteLength(preamble, "utf8");

if (preambleBytes > MAX_BYTES) {
  preamble = `PROJECT INTERFACE CONTRACT — FALLBACK PREAMBLE

WARNING: this hook's full preamble is ${preambleBytes}
bytes, above the ${MAX_BYTES} limit. It risked being truncated
by the harness. Report this to the user.

TO DO BEFORE ANY OTHER ACTION: read ${GLOBAL_CONTRACT} then
${CONTRACT_PATH} in full (Read tool).`;
}

const output = {
  hookSpecificOutput: {
    hookEventName: "SessionStart",
    additionalContext: preamble
  }
};

console.log(JSON.stringify(output));
