#!/usr/bin/env node
// SessionStart hook generated by agentic-agnostic-kit (Node.js engine).
//
// NEVER inline the full AGENTS.md contract here: a harness may truncate
// any large additionalContext. This hook emits a short preamble
// (< MAX_BYTES) extracted from the target contract's [PREAMBLE] section,
// plus the instruction to read the full contract.

import fs from "node:fs";
import path from "node:path";
import os from "node:os";

const GLOBAL_CONTRACT = path.join(os.homedir(), ".agents/AGENTS.md");
const PROJECT_DIR = process.env.CLAUDE_PROJECT_DIR || process.cwd();
const LOCAL_CONTRACT = path.join(PROJECT_DIR, ".agents/AGENTS.md");
const MAX_BYTES = 4096;

if (!fs.existsSync(GLOBAL_CONTRACT)) {
  process.exit(0);
}

function extractPreamble(filePath) {
  try {
    const content = fs.readFileSync(filePath, "utf-8");
    const regex = /<!-- agentic-agnostic-kit:begin:preamble[\s\S]*?-->\n([\s\S]*?)<!-- agentic-agnostic-kit:end:preamble.*?-->/;
    const match = content.match(regex);
    return match ? match[1].trim() : "";
  } catch (e) {
    return "";
  }
}

const preambleExcerpt = extractPreamble(GLOBAL_CONTRACT);

let localBlock = "";
if (fs.existsSync(LOCAL_CONTRACT) && LOCAL_CONTRACT !== GLOBAL_CONTRACT) {
  localBlock = `\n2. ALSO read ${LOCAL_CONTRACT} in full (project contract). In case of\n   conflict with the global contract, the project contract takes priority\n   for anything specific to this project.`;
}

let preamble = `INTERFACE CONTRACT — MANDATORY PREAMBLE

=== TO DO BEFORE ANY OTHER ACTION ===
1. Read ${GLOBAL_CONTRACT} in full (Read tool). The preamble below
   is an excerpt: it does not replace the contract.${localBlock}
These steps are required even if the user's first question seems
trivial or unrelated to code. Do not produce a substantive answer before that.

=== IMMEDIATE RULES (excerpt of the contract's [PREAMBLE] section) ===
${preambleExcerpt || "(no [PREAMBLE] section defined in the contract - refer to the full contract)"}`;

const preambleBytes = Buffer.byteLength(preamble, "utf8");

if (preambleBytes > MAX_BYTES) {
  preamble = `INTERFACE CONTRACT — FALLBACK PREAMBLE

WARNING: this hook's full preamble is ${preambleBytes}
bytes, above the ${MAX_BYTES} limit. Report this to
the user and shorten the contract's [PREAMBLE] section
(${GLOBAL_CONTRACT}).

TO DO BEFORE ANY OTHER ACTION: read ${GLOBAL_CONTRACT} in full
(Read tool), and ${LOCAL_CONTRACT} if it exists.`;
}

const output = {
  hookSpecificOutput: {
    hookEventName: "SessionStart",
    additionalContext: preamble
  }
};

console.log(JSON.stringify(output));
