#!/bin/bash
# SessionStart hook generated by agentic-agnostic-kit.
#
# NEVER inline the full AGENTS.md contract here: a harness may truncate
# any large additionalContext. This hook emits a short preamble
# (< MAX_BYTES) extracted from the target contract's [PREAMBLE] section,
# plus the instruction to read the full contract.
# Design rationale: agentic-agnostic-kit development notes.
set -euo pipefail

GLOBAL_CONTRACT="$HOME/.agents/AGENTS.md"
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$PWD}"
LOCAL_CONTRACT="$PROJECT_DIR/.agents/AGENTS.md"
MAX_BYTES=4096

if [ ! -f "$GLOBAL_CONTRACT" ]; then
  exit 0
fi

extract_preamble() {
  awk '/<!-- agentic-agnostic-kit:begin:preamble/{flag=1; next} /<!-- agentic-agnostic-kit:end:preamble/{flag=0} flag' "$1" 2>/dev/null || true
}

PREAMBLE_EXCERPT="$(extract_preamble "$GLOBAL_CONTRACT")"

LOCAL_BLOCK=""
if [ -f "$LOCAL_CONTRACT" ] && [ "$LOCAL_CONTRACT" != "$GLOBAL_CONTRACT" ]; then
  LOCAL_BLOCK="
2. ALSO read ${LOCAL_CONTRACT} in full (project contract). In case of
   conflict with the global contract, the project contract takes priority
   for anything specific to this project."
fi

PREAMBLE="INTERFACE CONTRACT — MANDATORY PREAMBLE

=== TO DO BEFORE ANY OTHER ACTION ===
1. Read ${GLOBAL_CONTRACT} in full (Read tool). The preamble below
   is an excerpt: it does not replace the contract.${LOCAL_BLOCK}
These steps are required even if the user's first question seems
trivial or unrelated to code. Do not produce a substantive answer before that.

=== IMMEDIATE RULES (excerpt of the contract's [PREAMBLE] section) ===
${PREAMBLE_EXCERPT:-(no [PREAMBLE] section defined in the contract - refer to the full contract)}"

PREAMBLE_BYTES=$(printf '%s' "$PREAMBLE" | wc -c | tr -d ' ')

if [ "$PREAMBLE_BYTES" -gt "$MAX_BYTES" ]; then
  PREAMBLE="INTERFACE CONTRACT — FALLBACK PREAMBLE

WARNING: this hook's full preamble is ${PREAMBLE_BYTES}
bytes, above the ${MAX_BYTES} limit. Report this to
the user and shorten the contract's [PREAMBLE] section
(${GLOBAL_CONTRACT}).

TO DO BEFORE ANY OTHER ACTION: read ${GLOBAL_CONTRACT} in full
(Read tool), and ${LOCAL_CONTRACT} if it exists."
fi

jq -n --arg preamble "$PREAMBLE" '{
  "hookSpecificOutput": {
    "hookEventName": "SessionStart",
    "additionalContext": $preamble
  }
}'
